[packages.darwin]
brews = [
    "curl",
    "git",
    "gnupg",
    "wget",
    "openssh",
    "fish",
    "nushell",
    "mise",
    "exiftool",
    "ffmpeg",
    "ghostscript",
    "imagemagick",
    "composer",
    "php",
    "poppler",
    "lynx",
    "nmap",
    "wireshark",
    "mpv",
    "sevenzip",
    "mas",
]
