[[packages.darwin.mas]]
name = "1Password for Safari"
id = 1569813296

[[packages.darwin.mas]]
name = "Canva"
id = 897446215

[[packages.darwin.mas]]
name = "DigiDoc4"
id = 1370791134

[[packages.darwin.mas]]
name = "Infuse"
id = 1136220934

[[packages.darwin.mas]]
name = "Microsoft Excel"
id = 462058435

[[packages.darwin.mas]]
name = "Microsoft PowerPoint"
id = 462062816

[[packages.darwin.mas]]
name = "Microsoft Word"
id = 462054704

[[packages.darwin.mas]]
name = "Reeder"
id = 6475002485

[[packages.darwin.mas]]
name = "uBlock Origin Lite"
id = 6745342698

[[packages.darwin.mas]]
name = "Web eID"
id = 1576665083

[[packages.darwin.mas]]
name = "WhatsApp"
id = 310633997

[[packages.darwin.mas]]
name = "WireGuard"
id = 1451685025
