version: 1
git_protocol: ssh
editor:
prompt: enabled
prefer_editor_prompt: disabled
pager:
aliases:
http_unix_socket:
browser:
color_labels: enabled
accessible_colors: disabled
accessible_prompter: disabled
spinner: enabled
