[packages.windows]
scoop = [
    "main/curl",
    "git",
    "main/gnupg",
    "main/sqlite",
    "main/wget",
    "main/nu",
    "main/mise",
    "main/exiftool",
    "main/ffmpeg",
    "main/imagemagick",
    "main/composer",
    "main/php",
    "main/poppler",
    "main/lynx",
    # "main/nmap",
    # "extras/wireshark",
    "main/1password-cli",
    "main/balena-cli",
    "extras/discord",
    "extras/helium",
    "extras/libreoffice",
    "extras/mpv",
    "extras/raspberry-pi-imager",
    "extras/rustdesk",
    "extras/signal",
    "extras/tailscale",
    "extras/winbox",
    "extras/yubioauth",
    "extras/zed",
    # "7zip",
]
