[packages.windows]
scoop = [
    "curl",
    "git",
    "gnupg",
    "sqlite",
    "wget",
    "nu",
    "mise",
    "exiftool",
    "ffmpeg",
    "imagemagick",
    "composer",
    "php",
    "poppler",
    "lynx",
    "nmap",
    # "wireshark",
    "1password",
    "balenaetcher",
    "discord",
    "helium",
    "libreoffice",
    "mpv",
    "raspberry-pi-imager",
    "rustdesk",
    "signal",
    "tailscale",
    "winbox",
    "yubico-authenticator",
    "zed",
    "7zip",
]
