[packages.windows]
scoop = [
    "main/curl",
    # "7zip",
    # "main/git",
    "main/gnupg",
    "main/sqlite",
    "main/wget",
    "main/nu",
    "main/mise",
    "extras/vcredist2022",
    "main/exiftool",
    "main/ffmpeg",
    "main/imagemagick",
    "main/composer",
    "main/php",
    "main/poppler",
    "main/lynx",
    # "main/nmap",
    # "extras/wireshark",
    "main/1password-cli",
    "extras/helium",
    "extras/rustdesk",
    "extras/signal",
    "extras/tailscale",
    "extras/winbox",
    "extras/yubioath",
    "extras/zed",
]
