"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[[mgr.prepend_keymap]]
on   = "!"
for  = "unix"
run  = 'shell "$SHELL" --block'
desc = "Open $SHELL here"

[[mgr.prepend_keymap]]
on = [ "g", "r" ]
run = 'shell -- ya emit cd "$(git rev-parse --show-toplevel)"'

[[mgr.prepend_keymap]]
on = "<C-p>"
run = 'shell -- qlmanage -p "$@"'

[[mgr.prepend_keymap]]
on   = [ "g", "p" ]
run  = "cd ~/Documents/Projects"
desc = "Cd to ~/Documents/Projects"

[[mgr.prepend_keymap]]
on   = [ "g", "c" ]
run  = "cd ~/.config"
desc = "Cd to ~/.config"

[[mgr.prepend_keymap]]
on  = "M"
run = "plugin mount"

[[mgr.prepend_keymap]]
on   = [ "c", "m" ]
run  = "plugin chmod"
desc = "Chmod on selected files"

[[mgr.prepend_keymap]]
on   = "<C-g>"
run  = "plugin lazygit"
desc = "run lazygit"

[[mgr.prepend_keymap]]
on   = [ "g", "s", "n" ]
run  = "cd sftp://nas"
desc = "Go to nas"

[[mgr.prepend_keymap]]
on   = [ "g", "s", "a" ]
run  = "cd sftp://archive"
desc = "Go to archive"
