[packages.linux.arch]
pacman = [
    # Build tools (needed for AUR)
    "base-devel",
    "ghostty",
    "ttf-monaspace-variable",
    "flatpak",
    "tailscale",
    "wireshark-qt",
    "zed",
    "caligula",
]
