[packages.linux.arch]
pacman = [
    "base-devel",
    "curl",
    "git",
    "gnupg",
    "wget",
    "fish",
    "nushell",
    "mise",
    "perl-image-exiftool",
    "ffmpeg",
    "ghostscript",
    "imagemagick",
    "composer",
    "php",
    "poppler",
    "lynx",
    "nmap",
    "wireshark-cli",
    "wireshark-qt",
    "mpv",
    "7zip",
    "ghostty",
    "ttf-monaspace-variable",
    "flatpak",
    "tailscale",
    "wireshark-qt",
    "zed",
    "caligula",
]
