[packages.linux.arch]
pacman = [
    "base-devel",
    "curl",
    "git",
    "nushell",
    "mise",
    "perl-image-exiftool",
    "ffmpeg",
    "imagemagick",
    "poppler",
    "7zip",
    "ghostty",
    "ttf-monaspace-variable",
    "flatpak",
    "tailscale",
    "zed",
]
