connections:
  pg:
    protocol: postgresql
    username: local
    password: local
    hostname: localhost
    port: 5432
    database: local
  mysql:
    protocol: mysql
    username: local
    password: local
    hostname: localhost
    port: 3306
    database: local
  icd0007:
    protocol: mysql
    username: {{ onepasswordRead "op://Personal/smoe7oxcj5brituvxllr5npjgi/username" }}
    password: {{ onepasswordRead "op://Personal/smoe7oxcj5brituvxllr5npjgi/password" }}
    hostname: {{ onepasswordRead "op://Personal/smoe7oxcj5brituvxllr5npjgi/server" }}
    port: {{ onepasswordRead "op://Personal/smoe7oxcj5brituvxllr5npjgi/port" }}
    database: {{ onepasswordRead "op://Personal/smoe7oxcj5brituvxllr5npjgi/database" }}
