[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]

[settings.npm]
package_manager = "bun"

[tools]
bat = "latest"
bottom = "latest"
bun = "latest"
cargo-binstall = "latest"
"cargo:systemd-lsp" = "latest"
crush = "latest"
dua = "latest"
github-cli = "latest"
scooter = "latest"
fzf = "latest"
fd = "latest"
glow = "latest"
jj = "latest"
harper-ls = "latest"
go = "latest"
usql = "latest"
marksman = "latest"
pandoc = "latest"
rclone = "latest"
node = "latest"
lazygit = "latest"
yazi = "latest"
jq = "latest"
ripgrep = "latest"
usage = "latest"
resvg = "latest"
zoxide = "latest"
xh = "latest"
uv = "latest"
"pipx:ty" = "latest"
"cargo:mago" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:@markdoc/language-server" = "latest"
"cargo:oha" = "latest"
"cargo:csvlens" = "latest"
"cargo:rainfrog" = "latest"
"cargo:rumdl" = "latest"
"cargo:slumber" = "latest"
sqlite = "latest"
"go:github.com/sqls-server/sqls" = "latest"
"cargo:trippy" = "latest"
"github:spinel-coop/rv" = "latest"
rust = "latest"
lazydocker = "latest"
doggo = "latest"
"cargo:procs" = "latest"
grex = "latest"
"go:github.com/docker/docker-language-server/cmd/docker-language-server" = "latest"
"cargo:commit-lsp" = "latest"
tombi = "latest"
gofumpt = "latest"
yamlfmt = "latest"
tlrc = "latest"
"pipx:ansible" = "latest"
biome = "latest"
caddy = "latest"
chezmoi = "latest"
fnox = "latest"
gemini-cli = "latest"
helix = "latest"
hurl = "latest"
marp-cli = "latest"
yamllint = "latest"
terraform-ls = "latest"
prettier = "latest"
"cargo:bandwhich" = "latest"
lazyjournal = "latest"
"npm:bash-language-server" = "latest"
"pipx:ansible-lint" = "latest"
"npm:@ansible/ansible-language-server" = "latest"
"npm:fish-lsp" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"cargo:hl" = "latest"
"go:github.com/wader/jq-lsp" = "latest"
"npm:yaml-language-server" = "latest"
"npm:typescript-language-server" = "latest"
"cargo:topgrade" = "latest"
"pipx:posting" = "latest"
golangci-lint = "latest"
golangci-lint-langserver = "latest"
"pipx:ruff" = "latest"
