[settings]
experimental = true
color_theme = "dracula"
idiomatic_version_file_enable_tools = ["python", "node"]
trusted_config_paths = ["~/Documents/Projects"]

[settings.npm]
package_manager = "bun"

[settings.python]
uv_venv_auto = true

[tools]
node = "latest"
bun = "latest"
go = "latest"
rust = "latest"
sqlite = "latest"
uv = "latest"
cargo-binstall = "latest"
bottom = "latest"
dua = "latest"
bat = "latest"
yazi = "latest"
helix = "latest"
github-cli = "latest"
crush = "latest"
scooter = "latest"
xh = "latest"
lazydocker = "latest"
doggo = "latest"
grex = "latest"
tlrc = "latest"
caddy = "latest"
fzf = "latest"
fd = "latest"
glow = "latest"
jj = "latest"
usql = "latest"
marksman = "latest"
pandoc = "latest"
rclone = "latest"
lazygit = "latest"
jq = "latest"
ripgrep = "latest"
usage = "latest"
resvg = "latest"
zoxide = "latest"
chezmoi = "latest"
fnox = "latest"
gemini-cli = "latest"
lazyjournal = "latest"
hurl = "latest"
marp-cli = "latest"
golangci-lint = "latest"
golangci-lint-langserver = "latest"
biome = "latest"
tombi = "latest"
gofumpt = "latest"
yamlfmt = "latest"
yamllint = "latest"
prettier = "latest"
terraform-ls = "latest"
harper-ls = "latest"
"github:spinel-coop/rv" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:@markdoc/language-server" = "latest"
"npm:bash-language-server" = "latest"
"npm:fish-lsp" = "latest"
"npm:yaml-language-server" = "latest"
"npm:typescript-language-server" = "latest"
"go:golang.org/x/tools/gopls" = "latest"
"go:github.com/sqls-server/sqls" = "latest"
"go:github.com/docker/docker-language-server/cmd/docker-language-server" = "latest"
"go:github.com/wader/jq-lsp" = "latest"
"pipx:posting" = "latest"
"cargo:systemd-lsp" = "latest"
"cargo:mago" = "latest"
"cargo:oha" = "latest"
"cargo:csvlens" = "latest"
"cargo:rainfrog" = "latest"
"cargo:slumber" = "latest"
"cargo:trippy" = "latest"
"cargo:procs" = "latest"
"cargo:commit-lsp" = "latest"
"cargo:bandwhich" = "latest"
"cargo:hl" = "latest"
"cargo:topgrade" = "latest"
codex = "latest"
claude-code = { version = "latest", bin = "claude", platforms = """
[linux-arm64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{version}/linux-arm64/claude"

[linux-x64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{version}/linux-x64/claude"

[macos-arm64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{version}/darwin-arm64/claude"

[macos-x64]
url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/{version}/darwin-x64/claude"
""", version_list_url = "https://storage.googleapis.com/claude-code-dist-86c565f3-f756-42ad-8dfa-d59b1c096819/claude-code-releases/latest" }
starship = "latest"
ty = "latest"
rumdl = "latest"
ruff = "latest"
ruby = "latest"
"cargo:mq-run" = "latest"
"cargo:Feel-ix-343/markdown-oxide" = "latest"
"github:pranshuparmar/witr" = "latest"
eza = "latest"
