[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]

[settings.npm]
package_manager = "bun"

[tools]
bat = "latest"
bottom = "latest"
bun = "latest"
cargo-binstall = "latest"
"cargo:systemd-lsp" = "latest"
crush = "latest"
dua = "latest"
github-cli = "latest"
scooter = "latest"
fzf = "latest"
fd = "latest"
glow = "latest"
jj = "latest"
harper-ls = "latest"
go = "latest"
usql = "latest"
marksman = "latest"
pandoc = "latest"
rclone = "latest"
node = "latest"
lazygit = "latest"
yazi = "latest"
jq = "latest"
ripgrep = "latest"
usage = "latest"
resvg = "latest"
zoxide = "latest"
xh = "latest"
uv = "latest"
"pipx:ty" = "latest"
"cargo:mago" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:@markdoc/language-server" = "latest"
ruff = "latest"
"cargo:oha" = "latest"
"cargo:csvlens" = "latest"
"cargo:rainfrog" = "latest"
"cargo:rumdl" = "latest"
"cargo:slumber" = "latest"
sqlite = "latest"
"go:github.com/sqls-server/sqls" = "latest"
"cargo:trippy" = "latest"
"github:spinel-coop/rv" = "latest"
1password = "latest"
rust = "latest"
lazydocker = "latest"
doggo = "latest"
"cargo:procs" = "latest"
grex = "latest"
"go:github.com/docker/docker-language-server/cmd/docker-language-server" = "latest"
"cargo:commit-lsp" = "latest"
tombi = "latest"
gofumpt = "latest"
yamlfmt = "latest"
tlrc = "latest"
