[settings]
experimental = true
color_theme = "catppuccin"
idiomatic_version_file_enable_tools = ["python", "node"]
trusted_config_paths = ["~/Documents/Projects", "/workspaces"]

[settings.npm]
package_manager = "bun"

[settings.python]
uv_venv_auto = true

[tools]
node = "latest"
bun = "latest"
go = "latest"
rust = "latest"
uv = "latest"
cargo-binstall = "latest"
bottom = "latest"
dua = "latest"
bat = "latest"
yazi = "latest"
# helix = "latest"
github-cli = "latest"
scooter = "latest"
xh = "latest"
lazydocker = "latest"
doggo = "latest"
grex = "latest"
tlrc = "latest"
fzf = "latest"
fd = "latest"
glow = "latest"
jj = "latest"
usql = "latest"
marksman = "latest"
pandoc = "latest"
lazygit = "latest"
jq = "latest"
ripgrep = "latest"
usage = "latest"
resvg = "latest"
zoxide = "latest"
chezmoi = "latest"
tombi = "latest"
yamlfmt = "latest"
yamllint = "latest"
harper-ls = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:@markdoc/language-server" = "latest"
"npm:bash-language-server" = "latest"
"npm:yaml-language-server" = "latest"
"cargo:systemd-lsp" = "latest"
"cargo:csvlens" = "latest"
"cargo:rainfrog" = "latest"
"cargo:trippy" = "latest"
"cargo:procs" = "latest"
"cargo:bandwhich" = "latest"
"cargo:topgrade" = "latest"
starship = "latest"
rumdl = "latest"
"github:pranshuparmar/witr" = "latest"
eza = "latest"
biome = "latest"
jbang = "latest"
opencode = "latest"
"cargo:caligula" = "latest"
